import { TrendingUp, TrendingDown, Lightbulb, Info } from 'lucide-react';
import './ExplanationPanel.css';

/**
 * ExplanationPanel Component
 * Displays AI decision factors in plain language
 * Shows top contributors, directional impact, and actionable advice
 */
export default function ExplanationPanel({ factors, tier, counterfactuals }) {
    // Mock data structure (in production, comes from backend XAI service)
    const defaultFactors = factors || [
        { name: 'Credit Score', impact: 'positive', strength: 'high', description: 'Your credit score is in the good range' },
        { name: 'Debt-to-Income Ratio', impact: 'negative', strength: 'medium', description: 'Your monthly debt payments are relatively high compared to income' },
        { name: 'Payment History', impact: 'positive', strength: 'medium', description: 'You have a consistent record of on-time payments' }
    ];

    const defaultCounterfactuals = counterfactuals || [
        { suggestion: 'Reducing your total debt by $5,000 would likely improve your approval chances', actionable: true },
        { suggestion: 'Increasing your annual income documentation could strengthen your application', actionable: true }
    ];

    const getImpactIcon = (impact) => {
        return impact === 'positive' ?
            <TrendingUp size={18} className="impact-icon positive" /> :
            <TrendingDown size={18} className="impact-icon negative" />;
    };

    const getStrengthLabel = (strength) => {
        if (strength === 'high') return 'Strong influence';
        if (strength === 'medium') return 'Moderate influence';
        return 'Minor influence';
    };

    return (
        <div className="explanation-panel">
            <div className="explanation-header">
                <Info size={20} />
                <h3>Why this decision?</h3>
            </div>

            <p className="explanation-intro">
                Our AI analyzed several factors in your application. Here's what influenced the decision:
            </p>

            {/* Top Contributing Factors */}
            <div className="factors-section">
                <h4>Key Factors</h4>
                <div className="factors-list">
                    {defaultFactors.map((factor, idx) => (
                        <div key={idx} className="factor-item">
                            <div className="factor-header">
                                {getImpactIcon(factor.impact)}
                                <div className="factor-info">
                                    <span className="factor-name">{factor.name}</span>
                                    <span className="factor-strength">{getStrengthLabel(factor.strength)}</span>
                                </div>
                            </div>
                            <p className="factor-description">{factor.description}</p>
                        </div>
                    ))}
                </div>
            </div>

            {/* Counterfactual Advice */}
            {tier !== 'Approve' && (
                <div className="advice-section">
                    <div className="advice-header">
                        <Lightbulb size={20} />
                        <h4>How to improve</h4>
                    </div>
                    <p className="advice-intro">
                        Based on our analysis, here are some steps that could strengthen future applications:
                    </p>
                    <ul className="advice-list">
                        {defaultCounterfactuals.map((item, idx) => (
                            <li key={idx} className={item.actionable ? 'actionable' : ''}>
                                {item.suggestion}
                            </li>
                        ))}
                    </ul>
                </div>
            )}

            {/* Disclaimer */}
            <div className="explanation-footer">
                <p>
                    <strong>Important:</strong> This explanation is generated by AI and represents one interpretation of your application.
                    A human underwriter will review all factors before making a final decision.
                </p>
            </div>
        </div>
    );
}
