"""Add decision_id to ManualReview

Revision ID: 38082d8ba07a
Revises: c9790637e7d8
Create Date: 2026-01-07 19:11:40.713276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38082d8ba07a'
down_revision: Union[str, Sequence[str], None] = 'c9790637e7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('manual_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decision_id', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_manual_reviews_decisions', 'decisions', ['decision_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'manual_reviews', type_='foreignkey')
    op.drop_column('manual_reviews', 'decision_id')
    # ### end Alembic commands ###
